/**
 * The demo couple, Sarah and James.
 *
 * ── WHY IT IS A MODULE ────────────────────────────────────────────────────
 * These four answer sets were written inline inside App(), which meant nothing
 * outside the website's bundle could read them. That is not a tidiness problem:
 * it is why there is no check that the website's results and the app's agree.
 *
 * The app reads /api/results and draws the payload. The website imports the
 * pieces and composes the sections itself, so every condition deciding whether a
 * block appears exists twice, and the only way to compare the two is to run both
 * over the SAME couple. There was no same couple to run them over.
 *
 * Conflict Patterns already went through this. api/_lib/conflict-demo.js says so
 * in its own header: it exists "so there is one demo couple rather than two
 * drifting apart". This is the same move for Communication and Expectations.
 *
 * ── WHAT THESE ARE ────────────────────────────────────────────────────────
 * Raw answers, exactly as a real couple's would be stored: question id to a
 * number for Communication, and the nested shape Expectations saves for its five
 * parts. Nothing derived, nothing pre-scored. They are moved here verbatim, so
 * the demo a reviewer has been looking at is unchanged.
 *
 * The `{userName}` and `{partnerName}` inside some Expectations keys are the
 * product's own placeholders, substituted when the row is drawn. They are part
 * of the key, not code.
 */

export const sarahEx1 = {
  en1:2,
  en2:2,
  en3:1,
  en4:2,
  en5:2,
  ex1:4,
  ex2:4,
  ex3:4,
  ex4:3,
  ex5:4,
  nd1:2,
  nd2:2,
  nd3:2,
  nd4:2,
  nd5:2,
  bd1:4,
  bd2:4,
  bd3:4,
  bd4:4,
  bd5:4,
  cf1:1,
  cf2:1,
  cf3:1,
  cf4:1,
  cf5:1,
  rp1:2,
  rp2:2,
  rp3:1,
  rp4:2,
  rp5:1,
  cl1:4,
  cl2:4,
  cl3:4,
  cl4:4,
  cl5:4,
  lv1:1,
  lv2:1,
  lv3:1,
  lv4:1,
  st1:5,
  st2:5,
  st3:5,
  st4:4,
  st5:5,
  fb1:4,
  fb2:4,
  fb3:4,
  fb4:4,
  fb5:4,
};
export const sarahEx2 = {
  childhoodStructure: "mom-dad",
  childhood: {
    "household__Cooking meals": "Mom",
    "household__Grocery shopping and meal planning": "Mom",
    "household__Keeping the home tidy day-to-day": "Mom",
    "household__Managing home repairs and maintenance": "Dad",
    "household__Managing the family calendar": "Mom",
    "household__Planning and organizing social events, holidays, and gatherings": "Mom",
    "household__Planning and booking vacations": "Both",
    "financial__Paying bills and managing day-to-day finances": "Dad",
    "financial__Making major financial decisions": "Dad",
    "financial__Managing savings and investments": "Dad",
    "financial__Filing taxes": "Dad",
    "career__Being the primary income earner": "Dad",
    "career__Whose career shapes major family decisions, where you live, your schedule, your lifestyle": "Dad",
    "career__Who makes career sacrifices when the family needs it": "Mom",
    "emotional__Carrying the mental load, remembering, anticipating, planning ahead": "Mom",
    "emotional__Tracking the emotional wellbeing of the household": "Mom",
    "emotional__Maintaining closeness and emotional intimacy over time": "Mom",
    "emotional__Initiating difficult conversations": "Mom",
    "emotional__Being the first to reach out after conflict": "Mom",
  },
  responsibilities: {
    "household__Grocery shopping and meal planning": "Sarah",
    "household__Keeping the home tidy day-to-day": "Both of us",
    "household__Managing home repairs and maintenance": "James",
    "household__Managing the family calendar": "Sarah",
    "household__Planning and organizing social events, holidays, and gatherings": "Sarah",
    "household__Planning and booking vacations": "Both of us",
    "financial__Paying bills and managing day-to-day finances": "James",
    "financial__Making major financial decisions": "Both of us",
    "financial__Managing savings and investments": "James",
    "financial__Filing taxes": "James",
    "career__Being the primary income earner": "Both of us",
    "career__Whose career shapes major family decisions, where you live, your schedule, your lifestyle": "Both of us",
    "career__Who makes career sacrifices when the family needs it": "Both of us",
    "emotional__Carrying the mental load, remembering, anticipating, planning ahead": "Sarah",
    "emotional__Tracking the emotional wellbeing of the household": "Sarah",
    "emotional__Maintaining closeness and emotional intimacy over time": "Both of us",
    "emotional__Initiating difficult conversations": "Both of us",
    "emotional__Being the first to reach out after conflict": "Sarah",
    "extended_family__Planning visits with {userName}'s family": "Sarah",
    "extended_family__Gifting for {userName}'s family": "Sarah",
    "extended_family__Planning visits with {partnerName}'s family": "Both of us",
    "extended_family__Gifting for {partnerName}'s family": "Sarah",
  },
  life: {
    lq_children: "Important to me, I want at least one",
    lq_family_conf: "Side with my partner, they're my primary family now",
    lq_location: "I have a preference but I'm open to discussion",
    lq_social: "A healthy balance of time together and time with others",
    lq_routine: "Prefers a loose rhythm but likes knowing the plan",
    lq_faith: "Is personal to me but wouldn't shape our shared life",
    lq_values: "Share broadly similar values even if the details differ",
    lq_finances: "Mostly combined with some personal spending money for each of us",
    lq_money_lean: "Toward saving, but you live well along the way",
    lq_money_risk: "I'm cautious but open to calculated risks",
  }
};
export const jamesEx1 = {
  en1:4,
  en2:4,
  en3:4,
  en4:4,
  en5:4,
  ex1:2,
  ex2:2,
  ex3:2,
  ex4:2,
  ex5:2,
  nd1:4,
  nd2:4,
  nd3:4,
  nd4:4,
  nd5:4,
  bd1:2,
  bd2:2,
  bd3:2,
  bd4:2,
  bd5:2,
  cf1:5,
  cf2:5,
  cf3:5,
  cf4:5,
  cf5:5,
  rp1:4,
  rp2:4,
  rp3:4,
  rp4:4,
  rp5:4,
  cl1:2,
  cl2:2,
  cl3:2,
  cl4:2,
  cl5:2,
  lv1:5,
  lv2:5,
  lv3:5,
  lv4:5,
  st1:1,
  st2:1,
  st3:1,
  st4:1,
  st5:1,
  fb1:2,
  fb2:2,
  fb3:2,
  fb4:2,
  fb5:2
};

export const jamesEx2 = {
  childhoodStructure: "mom-dad",
  childhood: {
    "household__Cooking meals": "Mom",
    "household__Grocery shopping and meal planning": "Mom",
    "household__Keeping the home tidy day-to-day": "Mom",
    "household__Managing home repairs and maintenance": "Dad",
    "household__Managing the family calendar": "Mom",
    "household__Planning and organizing social events, holidays, and gatherings": "Both",
    "household__Planning and booking vacations": "Dad",
    "financial__Paying bills and managing day-to-day finances": "Dad",
    "financial__Making major financial decisions": "Dad",
    "financial__Managing savings and investments": "Dad",
    "financial__Filing taxes": "Dad",
    "career__Being the primary income earner": "Dad",
    "career__Whose career shapes major family decisions, where you live, your schedule, your lifestyle": "Dad",
    "career__Who makes career sacrifices when the family needs it": "Mom",
    "emotional__Carrying the mental load, remembering, anticipating, planning ahead": "Mom",
    "emotional__Tracking the emotional wellbeing of the household": "Mom",
    "emotional__Maintaining closeness and emotional intimacy over time": "Mom",
    "emotional__Initiating difficult conversations": "Dad",
    "emotional__Being the first to reach out after conflict": "Dad",
  },
  responsibilities: {
    "household__Cooking meals": "Sarah",
    "household__Grocery shopping and meal planning": "Both of us",
    "household__Keeping the home tidy day-to-day": "Both of us",
    "household__Managing home repairs and maintenance": "James",
    "household__Managing the family calendar": "Both of us",
    "household__Planning and organizing social events, holidays, and gatherings": "Both of us",
    "household__Planning and booking vacations": "James",
    "financial__Paying bills and managing day-to-day finances": "Both of us",
    "financial__Making major financial decisions": "Both of us",
    "financial__Managing savings and investments": "Both of us",
    "financial__Filing taxes": "Both of us",
    "career__Being the primary income earner": "Both of us",
    "career__Whose career shapes major family decisions, where you live, your schedule, your lifestyle": "James",
    "career__Who makes career sacrifices when the family needs it": "Both of us",
    "emotional__Carrying the mental load, remembering, anticipating, planning ahead": "Both of us",
    "emotional__Tracking the emotional wellbeing of the household": "Both of us",
    "emotional__Maintaining closeness and emotional intimacy over time": "Both of us",
    "emotional__Initiating difficult conversations": "Both of us",
    "emotional__Being the first to reach out after conflict": "James",
    "extended_family__Planning visits with {userName}'s family": "James",
    "extended_family__Gifting for {userName}'s family": "Both of us",
    "extended_family__Planning visits with {partnerName}'s family": "Both of us",
    "extended_family__Gifting for {partnerName}'s family": "James",
  },
  life: {
    lq_children: "Important to me, I want at least one",
    lq_family_conf: "Mediate fairly, I won't automatically take either side",
    lq_location: "I'd go wherever makes the most sense for us as a unit",
    lq_social: "Quiet by default with room for social when we choose it",
    lq_routine: "Needs a lot of structure and routine to feel grounded",
    lq_faith: "Plays no role, it's not part of how I live",
    lq_values: "Share broadly similar values even if the details differ",
    lq_finances: "Mostly combined with some personal spending money for each of us",
    lq_money_lean: "Neither way strongly, it depends on the situation",
    lq_money_risk: "I'm comfortable with risk if we've thought it through together",
  }
};
// Demo: start with pre-populated answers to show results immediately.
// In production, these would be null until the user completes each exercise.
// Demo pre-populated Sarah answers so all exercises and Results are accessible
