/**
 * Which version of the legal documents a person agreed to.
 *
 * GENERATED by scripts/build-legal-version.mjs. Do not edit.
 *
 * It is a hash of the text of the Privacy Policy and the Terms of Service on
 * public/legal.html, which is what makes a consent record mean something: it
 * says exactly which words were on the page, and it changes the moment they
 * do. A date could not do that, and two of those documents are published
 * today with no date at all.
 */
export const LEGAL_VERSION = '41fccaf2564a';

/** The documents the version covers, in the order they are hashed. */
export const LEGAL_DOCUMENTS = ["privacy","terms"];
