// Fails the build when a launch flag exists in more than one place.
//
// ── THE RULE ───────────────────────────────────────────────────────────────
// Whether the app is in the App Store, what the listing URL is, and whether
// physical packages are sold are three facts. Each is declared once, in
// api/_lib/flags.js, and every surface reads it from there.
//
// They were declared four times: public/_flags.js for the static pages,
// src/App.jsx for the portal, api/send-order-email.js as APP_LIVE, and
// api/create-payment-intent.js from an environment variable. Every copy
// carried a comment asking the next person to keep it in sync with the
// others. src/App.jsx said "Nothing else needs changing".
//
// Nothing had broken yet, because every flag is false and false is false four
// times over. The day it breaks is the day the app reaches the App Store and
// four files plus an environment variable have to change together, one of
// them an email template nobody opens until a customer says the link is dead.
//
// ── WHAT THIS CHECKS ───────────────────────────────────────────────────────
// 1. public/_flags.js carries exactly the values the module holds. It is
//    generated by scripts/build-flags.mjs and committed, so it can drift by
//    hand between builds.
// 2. No other file declares one of these names as its own constant.
//
// ── WHAT IT DOES NOT COVER ─────────────────────────────────────────────────
// ATTUNE_PHYSICAL_ENABLED, the environment override in create-payment-intent.
// A gate cannot read Vercel's environment. That override can only turn
// physical on, never off, so the worst it can do is enable something the code
// disabled, which is a deliberate act by whoever set it rather than drift.

import { readFileSync, readdirSync, statSync } from 'fs';
import { join } from 'path';
import { ATTUNE_FLAGS } from '../api/_lib/flags.js';

const ROOT = new URL('..', import.meta.url).pathname;
const SOURCE = 'api/_lib/flags.js';
const GENERATED = 'public/_flags.js';

const problems = [];

// ── 1. The generated file agrees with the module ──────────────────────────
const generated = readFileSync(join(ROOT, GENERATED), 'utf8');
const block = generated.match(/window\.ATTUNE_FLAGS = \{([\s\S]*?)\n\};/);
if (!block) {
  problems.push(`${GENERATED} has no window.ATTUNE_FLAGS object. Run node scripts/build-flags.mjs.`);
} else {
  for (const [key, value] of Object.entries(ATTUNE_FLAGS)) {
    const found = block[1].match(new RegExp(`${key}:\\s*('[^']*'|true|false)`));
    if (!found) {
      problems.push(`${GENERATED} does not carry ${key}. Run node scripts/build-flags.mjs.`);
      continue;
    }
    const written = found[1].replace(/^'|'$/g, '');
    const expected = String(value);
    if (written !== expected) {
      problems.push(
        `${GENERATED} has ${key} = ${written}; ${SOURCE} says ${expected}.\n`
        + '      The static pages and the portal would disagree about the same fact.\n'
        + '      Run node scripts/build-flags.mjs.');
    }
  }
}

// ── 2. Nobody else declares one ───────────────────────────────────────────
// The names as they appear when someone re-declares the fact rather than
// importing it. APP_BANNER_ENABLED is on the list because that is the name the
// portal used for what the module calls APP_LIVE: a second name for one fact
// is how it hid for as long as it did.
const NAMES = ['APP_LIVE', 'APP_BANNER_ENABLED', 'APP_STORE_URL', 'PHYSICAL_ENABLED'];
const DECLARES = new RegExp(
  `^\\s*(?:export\\s+)?(?:const|let|var)\\s+(${NAMES.join('|')})\\s*=([^;\\n]*)`, 'm');

const files = [];
for (const dir of ['api', 'src', 'scripts', 'public']) {
  (function walk(d) {
    for (const f of readdirSync(join(ROOT, d))) {
      const rel = join(d, f);
      const abs = join(ROOT, rel);
      if (statSync(abs).isDirectory()) { walk(rel); continue; }
      if (/\.(js|jsx|mjs)$/.test(f)) files.push(rel);
    }
  })(dir);
}

for (const rel of files) {
  if (rel === SOURCE || rel === GENERATED) continue;
  const src = readFileSync(join(ROOT, rel), 'utf8');
  const m = src.match(DECLARES);
  if (!m) continue;

  // A declaration that reads the module is not a second copy. Deriving a local
  // name from the imported one is the point: create-payment-intent.js writes
  //
  //   const PHYSICAL_ENABLED = process.env.ATTUNE_PHYSICAL_ENABLED === '1'
  //     || FLAG_PHYSICAL_ENABLED;
  //
  // so the environment can widen the flag but the flag is still the source.
  const imported = src.match(/import\s*\{([^}]*)\}\s*from\s*'[^']*_lib\/flags\.js'/);
  if (imported) {
    const bindings = imported[1]
      .split(',')
      .map((b) => b.split(/\s+as\s+/).pop().trim())
      .filter(Boolean);
    if (bindings.some((b) => new RegExp(`\\b${b}\\b`).test(m[2]))) continue;
  }

  problems.push(
    `${rel} declares ${m[1]} itself.\n`
    + `      It is one of three facts that live in ${SOURCE}. Import it from there:\n`
    + '      a second copy is only ever discovered by a customer.');
}

if (files.length < 20) {
  console.error(`[check-flags] only scanned ${files.length} files; refusing to pass.`);
  process.exit(1);
}

if (problems.length) {
  console.error('[check-flags] a launch flag exists in more than one place:');
  for (const p of problems) console.error(`  ${p}`);
  process.exit(1);
}

console.log(
  `[check-flags] ${Object.keys(ATTUNE_FLAGS).length} flags, one source, `
  + `${files.length} files scanned; no second copy.`);
