-- Migration 067: a couple you can sign in as
-- ============================================================================
-- GENERATED by scripts/build-test-couple.mjs. Regenerate rather than edit.
--
-- Ellie: "Can you build me a fake login with a partner who has already
-- completed their exercises, so that I can go through the full process in the
-- simulator?"
--
--   Sign in as   tester@attune-relationships.com
--   Password     AttuneTest2026
--
-- That account owns everything: premium plus every add-on. It has answered
-- nothing, which is the point. Its partner, tester-partner@attune-relationships.com,
-- has finished all five exercises, so results unlock the moment you finish
-- yours and the workbook builds itself at that moment.
--
-- ── WHAT IT WRITES ────────────────────────────────────────────────────────
--   two rows in auth.users and their auth.identities, so both can sign in
--   two rows in public.profiles, linked to each other
--   one row in public.orders carrying premium and every add-on
--
-- Everything is ON CONFLICT DO NOTHING, so running it twice changes nothing.
-- To start the walkthrough again, run the reset at the bottom, which clears
-- the tester's own answers and leaves the partner's alone.
--
-- Run in the Supabase SQL Editor and click Run.
-- ============================================================================

-- ── The two accounts ───────────────────────────────────────────────────────
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password,
  email_confirmed_at, created_at, updated_at,
  raw_app_meta_data, raw_user_meta_data,
  -- ── WHY THE EMPTY STRINGS ───────────────────────────────────────────
  -- Supabase's auth service reads these as text, not as nullable text. A
  -- row inserted without them has nulls, and every sign-in for that user
  -- fails inside the service before it ever checks the password: the app
  -- shows "something went wrong on our end" and the log says nothing
  -- useful. They are empty strings on a real signup too.
  confirmation_token, recovery_token, email_change_token_new, email_change,
  email_change_token_current, phone_change, phone_change_token,
  reauthentication_token
)
values
  ('00000000-0000-0000-0000-000000000000', '11111111-1111-4111-8111-111111111111', 'authenticated', 'authenticated',
   'tester@attune-relationships.com', crypt('AttuneTest2026', gen_salt('bf')),
   now(), now(), now(), '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb,
   '', '', '', '', '', '', '', ''),
  ('00000000-0000-0000-0000-000000000000', '22222222-2222-4222-8222-222222222222', 'authenticated', 'authenticated',
   'tester-partner@attune-relationships.com', crypt('AttuneTest2026', gen_salt('bf')),
   now(), now(), now(), '{"provider":"email","providers":["email"]}'::jsonb, '{}'::jsonb,
   '', '', '', '', '', '', '', '')
on conflict (id) do nothing;

-- Supabase looks an email sign-in up through identities, not through
-- auth.users alone. Without these rows the password is right and the sign-in
-- still fails.
--
-- Wrapped, because this table's columns have changed across Supabase versions:
-- provider_id arrived later, and older projects have an id column with no
-- default. If it cannot be written the notice says so and everything else in
-- this file still lands; the accounts then need the identity added by hand, or
-- through the dashboard's own "add user".
do $$
begin
  insert into auth.identities (provider_id, user_id, identity_data, provider, last_sign_in_at, created_at, updated_at)
  values
    ('11111111-1111-4111-8111-111111111111', '11111111-1111-4111-8111-111111111111',
     '{"sub":"11111111-1111-4111-8111-111111111111","email":"tester@attune-relationships.com","email_verified":true,"phone_verified":false}'::jsonb,
     'email', now(), now(), now()),
    ('22222222-2222-4222-8222-222222222222', '22222222-2222-4222-8222-222222222222',
     '{"sub":"22222222-2222-4222-8222-222222222222","email":"tester-partner@attune-relationships.com","email_verified":true,"phone_verified":false}'::jsonb,
     'email', now(), now(), now())
  on conflict do nothing;
exception when others then
  raise notice 'identities not written (%), sign-in may need one added by hand', sqlerrm;
end $$;

-- ── The two profiles ───────────────────────────────────────────────────────
-- relationship_status decides which wording Physical Intimacy Expectations
-- uses: eleven of its eighteen questions are asked one way of a couple who are
-- already intimate and another way of a couple who are not yet, and anything
-- that is not married or remarried gets the second. A test couple with no
-- status was being asked the whole exercise the wrong way round.
insert into public.profiles (id, email, name, pronouns, partner_name, partner_pronouns, partner_email, pkg, relationship_status, profile_setup_complete)
values
  ('11111111-1111-4111-8111-111111111111', 'tester@attune-relationships.com', 'Tester', 'they/them', 'Testpartner', 'they/them', 'tester-partner@attune-relationships.com', 'premium', 'married', true),
  ('22222222-2222-4222-8222-222222222222', 'tester-partner@attune-relationships.com', 'Testpartner', 'they/them', 'Tester', 'they/them', 'tester@attune-relationships.com', 'premium', 'married', true)
on conflict (id) do nothing;

-- Linked to each other, owning everything. Written as an update as well as an
-- insert so a second run repairs a half-made couple rather than skipping it.
update public.profiles set
  partner_profile_id = '22222222-2222-4222-8222-222222222222',
  partner_joined = true,
  pkg = 'premium',
  addon_reflection = true, addon_intimacy = true, addon_conflict = true,
  addon_budget = true, addon_checklist = true, addon_workbook = true,
  profile_setup_complete = true
where id = '11111111-1111-4111-8111-111111111111';

update public.profiles set
  partner_profile_id = '11111111-1111-4111-8111-111111111111',
  partner_joined = true,
  joined_via_invite = true,
  pkg = 'premium',
  addon_reflection = true, addon_intimacy = true, addon_conflict = true,
  addon_budget = true, addon_checklist = true, addon_workbook = true,
  profile_setup_complete = true,
  ex1_answers = '{"en6":2,"pv_en6":2,"en4":5,"pv_en4":5,"ex6":2,"pv_ex6":2,"ex7":3,"pv_ex7":3,"ex8":4,"pv_ex8":4,"rs3":2,"pv_rs3":2,"rs1":5,"pv_rs1":5,"lv1":2,"pv_lv1":2,"lv2":3,"pv_lv2":3,"nd5":5,"pv_nd5":5,"nd1":1,"pv_nd1":1,"bd1":4,"pv_bd1":4,"bd3":1,"pv_bd3":1,"bd4":2,"pv_bd4":2,"ls1":4,"pv_ls1":4,"ls3":1,"pv_ls3":1,"cf1":2,"pv_cf1":2,"cf2":3,"pv_cf2":3,"cf3":4,"pv_cf3":4,"st1":2,"pv_st1":2,"rp3":4,"pv_rp3":4,"rp2":3,"pv_rp2":3,"rp6":2,"pv_rp6":2,"fb5":5,"pv_fb5":5,"fb2":2,"pv_fb2":2}'::jsonb,
  ex1_completed = true, ex1_completed_at = now(),
  ex2_answers = '{"responsibilities":{"household__Cooking meals":"shared","household__Grocery shopping and meal planning":"me","household__Keeping the home tidy day-to-day":"partner","household__Managing home repairs and maintenance":"partner","household__Managing the family calendar":"shared","household__Planning and organizing social events, holidays, and gatherings":"shared","household__Planning and booking vacations":"partner","financial__Paying bills and managing day-to-day finances":"partner","financial__Making major financial decisions":"me","financial__Managing savings and investments":"me","financial__Filing taxes":"partner","career__Being the primary income earner":"partner","career__Whose career shapes major family decisions, where you live, your schedule, your lifestyle":"shared","career__Who makes career sacrifices when the family needs it":"shared","emotional__Carrying the mental load, remembering, anticipating, planning ahead":"partner","emotional__Tracking the emotional wellbeing of the household":"shared","extended_family__Planning visits with {userName}''s family":"shared","extended_family__Gifting for {userName}''s family":"me","extended_family__Planning visits with {partnerName}''s family":"shared","extended_family__Gifting for {partnerName}''s family":"me"},"life":{"lq_children":"Uncertain","lq_involve_user":"Minimal, by design","lq_involve_partner":"Very little, if any","lq_family_conf":"Keep the peace","lq_location":"Genuinely open","lq_social":"Very social","lq_routine":"Prefer open","lq_faith":"Meaningful role","lq_values":"Share broadly similar values","lq_finances":"Mostly separate, shared account for shared expenses","lq_money_lean":"Fully in the present","lq_money_risk":"Drawn to bold moves"},"childhood":{},"childhoodStructure":null}'::jsonb,
  ex2_completed = true, ex2_completed_at = now(),
  ex3_answers = '{"a0":4,"a_sat_conn":4,"a_sat_comm":2,"a_sat_fun":3,"a8":"A sample answer for How We''re Doing, written so the reflection pages have words to show."}'::jsonb,
  ex3_completed = true, ex3_completed_at = now(),
  intimacy_data = '{"answers":{"iq_freq_want":0.5,"iq_freq_relative":0,"iq_freq_meaning":0.75,"iq_init_who":0,"iq_init_feel":0.5,"iq_init_turndown":0,"iq_comfort_ease":1,"iq_comfort_safe":["desired","privacy"],"iq_comfort_off":0.5,"iq_comm_open":1,"iq_comm_moment":0.5,"iq_comm_debrief":0,"iq_adv_appetite":1,"iq_adv_suggest":0.75,"iq_adv_balance":1,"iq_mean_for":["security","ritual"],"iq_mean_disconnect":0.5,"iq_mean_hope":0},"variant":"married","completedAt":"2026-09-17T03:42:57.395Z"}'::jsonb,
  conflict_data = '{"answers":{"c0":3,"c1":"b","c2":"a","c_crit":0,"c_cont":1,"c_def":3,"c_stone":2,"c8":"Using humor","c9":"A sample answer for c9, long enough to read like something a person typed.","c_repair":["Directly asking what I need","Suggesting a pause","Naming that they see it from my side","Physical affection (a hug, holding hands)","Humor to break the tension","A genuine apology"],"c_topic":"b","c_grat":"A sample answer for c_grat, long enough to read like something a person typed."},"completedAt":"2026-09-17T03:42:57.396Z"}'::jsonb
where id = '22222222-2222-4222-8222-222222222222';

-- ── The order that pays for it ─────────────────────────────────────────────
-- Wrapped for the same reason: the profile columns above already grant
-- everything, so a missing column here costs the order row and nothing else.
do $$
begin
  insert into public.orders (order_num, user_id, buyer_email, pkg_key, addon_reflection, addon_intimacy, addon_conflict, addon_budget, addon_checklist, addon_workbook)
  values ('TEST-COUPLE-001', '11111111-1111-4111-8111-111111111111', 'tester@attune-relationships.com', 'premium', true, true, true, true, true, true)
  on conflict do nothing;
exception when others then
  raise notice 'order row not written (%), the profile grants still stand', sqlerrm;
end $$;

-- ── Start the walkthrough again ────────────────────────────────────────────
-- Uncomment and run to clear the tester's own answers, leaving the partner's.
--
-- update public.profiles set
--   ex1_answers = null, ex1_completed = false, ex1_completed_at = null, ex1_progress = null,
--   ex2_answers = null, ex2_completed = false, ex2_completed_at = null, ex2_progress = null,
--   ex3_answers = null, ex3_completed = false, ex3_completed_at = null, ex3_progress = null,
--   intimacy_data = null, conflict_data = null, results_last_opened_at = null
-- where id = '11111111-1111-4111-8111-111111111111';
-- delete from public.couple_results
--  where partner_a in ('11111111-1111-4111-8111-111111111111', '22222222-2222-4222-8222-222222222222')
--     or partner_b in ('11111111-1111-4111-8111-111111111111', '22222222-2222-4222-8222-222222222222');

-- ── Verification ───────────────────────────────────────────────────────────
select
  (select count(*) from auth.users where id in ('11111111-1111-4111-8111-111111111111', '22222222-2222-4222-8222-222222222222'))        as accounts,
  (select count(*) from auth.identities where user_id in ('11111111-1111-4111-8111-111111111111', '22222222-2222-4222-8222-222222222222')) as identities,
  (select count(*) from public.profiles where id in ('11111111-1111-4111-8111-111111111111', '22222222-2222-4222-8222-222222222222'))   as profiles,
  (select partner_profile_id from public.profiles where id = '11111111-1111-4111-8111-111111111111')             as tester_partner,
  (select ex1_completed and ex2_completed and ex3_completed
     from public.profiles where id = '22222222-2222-4222-8222-222222222222')                                    as partner_finished;
